# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{moviesort}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Luke Redpath"]
  s.date = %q{2009-11-14}
  s.default_executable = %q{moviesort}
  s.email = %q{luke@lukeredpath.co.uk}
  s.executables = ["moviesort"]
  s.files = [
    "Rakefile",
     "VERSION",
     "bin/moviesort",
     "features/sorting_tv_shows.feature",
     "features/step_definitions/sorting_tv_shows_steps.rb",
     "features/support/env.rb",
     "lib/moviesort/command_line.rb",
     "lib/moviesort/sorter.rb",
     "lib/moviesort/tv_show.rb",
     "test/sorter_test.rb",
     "test/test_helper.rb",
     "test/tv_show_test.rb"
  ]
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Small command-line utility for sorting downloaded TV shows and movies}
  s.test_files = [
    "test/sorter_test.rb",
     "test/test_helper.rb",
     "test/tv_show_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

